include: package:flutter_lints/flutter.yaml # Or whatever lint package you use

analyzer:

formatter:
  trailing_commas: preserve

linter:
  rules:
    non_constant_identifier_names: true
    prefer_const_constructors: true
